# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: \.(py|rst|md|yml)$
        exclude: ^(doc/build|dist)
    -   id: end-of-file-fixer
        files: \.(py|rst|md)$
        exclude: ^(doc/build|dist)
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.2
  hooks:
    # Run the linter.
    - id: ruff
