FROM ubuntu:groovy

MAINTAINER Bertrand Neron <bneron@pasteur.fr>

USER root
ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y &&\
    apt install -y --no-install-recommends hmmer python3 python3-pip git
RUN apt clean -y


RUN cd /tmp &&\
    git clone https://github.com/gem-pasteur/macsyfinder.git &&\
    cd macsyfinder &&\
    python3 -m pip install . &&\
    install -m 755 Docker/Macsyfinder/macsyfinder-entrypoint.sh /usr/local/bin &&\
    cd /tmp &&\
    rm -Rf macsyfinder

ENV DEBIAN_FRONTEND teletype
ENV PYTHONIOENCODING UTF-8

RUN useradd -m msf
USER msf
WORKDIR /home/msf

CMD ['macsyfinder', '--help']
ENTRYPOINT ["/usr/bin/bash", "-c", "macsyfinder-entrypoint.sh"]