#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This script check if you push a tag
# if yes check if the tag match to the version decalred in metadata.yml
# if yes it prevents the push until the tag and the version match
#
# This script is widely inspired from https://gist.github.com/farseerfc/0729c08cd7c82b07000f20105f733b17

remote="$1"
url="$2"

VERSION_FILE="metadata.yml"

tagref=$(grep -Po 'refs/tags/([^ ]*) ' </dev/stdin | head -n1 | cut -c11- | tr -d '[:space:]')


if [[ "$tagref" == ""  ]]; then
    ## pushing without --tags , exit normally
    exit 0
fi

yml_vers=$(grep "vers:" "${VERSION_FILE}" | cut -d ' ' -f 2- | tr -d '[:space:]')

if [[ "$tagref" == "$yml_vers" ]];
then
    ## tag matches ver
    exit 0
else
    Red=$'\e[1;31m'
    Green=$'\e[1;32m'
    Yello=$'\e[1;33m'
    Clear=$'\e[0m'
    echo "${Red}Tag name don't match metadata file. Preventing push.${Clear}"
    echo "${Yello}tag name: $tagref${Clear}"
    echo "${Yello}metadata version: $yml_vers${Clear}"
    echo "${Green}Please fix it:${Clear}"
    echo "${Green}  1. remove tag:${Clear} git tag -d ${tagref}"
    echo "${Green}  2. edit metadata.yml${Clear}"
    echo "${Green}  3. commit metadata.yml:${Clear} git commit -m \"fix metadata vers\" metadata.yml"
    echo "${Green}  4. tag again:${Clear} git tag ${tagref}"
    echo "${Green}  5. and push:${Clear} git push ${remote} ${tagref}"
    exit 1
fi

exit 0
